name: One step for
favicon: null
layout_spectrum: 0.10132732545025647
typography_spectrum: 0.60054044239223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6986201002728194
  lightness: 0.8387027205899358
  saturation: 0.7478475912939757
  rhythmicContrast: 0.39086128934286535
purpose: []
